apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: 192.168.1.183:443/myapp/front:f1.0
          env:
            - name: ACCOUNTBOOK_API_ADDR
              value: backend.default
          name: frontend
          ports:
            - containerPort: 3000
          volumeMounts:
          - name: ocr-image-volume
            mountPath: /frontend/ocrImage

      volumes:
      - name: ocr-image-volume
        hostPath:
          path: /home/kevin/ocrImage
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: frontend
